# Generated by Django 2.0.2 on 2018-04-24 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=500)),
                ('op1', models.CharField(max_length=100)),
                ('op2', models.CharField(max_length=100)),
                ('op3', models.CharField(max_length=100)),
                ('op4', models.CharField(max_length=100)),
                ('opcorrect', models.CharField(max_length=1)),
                ('type', models.CharField(default='D', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apti.Stream'),
        ),
    ]
