# Generated by Django 2.0.2 on 2018-04-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='img',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
